name: travel_planner_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  equatable: ^2.0.5
  intl: ^0.20.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    # - fonts/
  # fonts:
  #   - family: Lato
  #     fonts:
  #       - asset: fonts/Lato-Regular.ttf
  #       - asset: fonts/Lato-Italic.ttf
  #         style: italic
